apiVersion: v1
kind: Service
metadata:
  name: {{ include "nekocafe.fullname" . }}-reservation-service
  labels:
    {{- include "nekocafe.labels" . | nindent 4 }}
    app.kubernetes.io/component: reservation-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: reservation-service
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nekocafe.fullname" . }}-member-service
  labels:
    {{- include "nekocafe.labels" . | nindent 4 }}
    app.kubernetes.io/component: member-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: member-service
  ports:
    - name: http
      port: 8080
      targetPort: http
